### ISSUE TITLE
The Dropbox link for netCDF files is not valid anymore.

### ISSUE THREAD

**Issue by zxw0919** [Orion-AI-Lab/S4A-Models#1]
Hi author,

I found that the Dropbox link for netCDF files is not valid anymore. Could u please renew it? Thanks a lot!

**Comment by paren8esis** [comment]
Hello,

It seems that Dropbox banned this link due to excess traffic. We have updated the link and also added alternative Google Drive and HuggingFace sources. Please check the updated README file.

**Comment by zxw0919** [comment]
That helps a lot! Thanks!
