### ISSUE TITLE
Missing PatchesDataModule class?

### ISSUE THREAD

**Issue by ascidian-ai** [Orion-AI-Lab/S4A-Models#2]
Good day folks,

I noticed check_dataset.ipynb references a PatchesDataModule class/method however I couldn't find it in the utils.PAD_datamodule.
Is there perhaps a missing .py file ?

Many thanks!
Steven Tuften
Masters in AI student at Deakin University (Australia)

**Comment by paren8esis** [comment]
Hello!

Actually `PatchesDatamodule` was later renamed into `PAD_datamodule` but the notebook was not updated accordingly. We fixed this issue and also a bug on the data paths. Please check the updated notebook, it should work now!

Thanks for opening this issue.

**Comment by ascidian-ai** [comment]
Thankyou Maria! Appreciate the speedy response! Great paper and experiements which we're hoping to build upon. Ciao!
