### ISSUE TITLE
use of root_path_coco instead of root_path_netcdf when calling PADDataModule()

### ISSUE THREAD

**Issue by ascidian-ai** [Orion-AI-Lab/S4A-Models#3]
Hi folks,

I noticed the following code uses the old **root_path_coco** parameter instead of **root_path_netcdf** when calling **PADDataModule()**:
- pad_experiments.py | line 390 and 456
- compute_class_weights.py line 49
- visualize_predictions.py line 178

I'm guessing root_path_netcdf was substituted for root_path_coco as some point and not updated in the above.

Let me know if this is correct!

Ciao!

**Comment by paren8esis** [comment]
Hello,
Correct, thanks for catching this! The paths parameters were later renamed and the changes were not reflected to all files. It should be fixed with the latest commits. Please check!

**Comment by ascidian-ai** [comment]
Awesome. Thanks Mara!
