### ISSUE TITLE
queries on the simulation

### ISSUE THREAD

**Issue by Krish-newbie** [Orion-AI-Lab/S4A-Models#6]
Hello Sir/Madam,
 
i am working on running this code on AWS SageMaker Jupyter Notebooks. i have some questions. Appreciate if you can share some guidance on the same.

1) I am trying to pre-compute the median to reduce my training time. When i try to run the code as - is, i keep getting the error - too many indices for array, array is 4-dimensional, but 6 were indexed. That behavior is abnormal. I am only trying to run the scenario-3. Can you share some idea on if any changes to be made in the code?

2) Are you able to share a reference point on how much time it took for training and what type of machine was used for the training?

3) If i need to modify the code for a different country, are you able to share some guidance on it?

Appreciate your help on the same. It will greatly help to resolve an issue for me.

**Comment by paren8esis** [comment]
Hello,

Thanks for your interest in our work! I reply to your questions below:

1. Could you please provide the command you are running as well as the full stack trace of the error?
2. The hardware we used for our experiments is a machine with three GPUs: 2 x NVIDIA GeForce 3080 and 1 x NVIDIA GeForce 3090, and an SSD drive for the data, so it took only a few hours to train each model. In any case, I would suggest a GPU with at least 11 GB RAM for fast experimentation. Even with a single GPU of such range I guess it won't take more than 1-2 days for each model.
3. We will try to help. Do you have any specific questions?

**Comment by Krish-newbie** [comment]
Hello,

Thank you for your quick response.

1. %run -i 'export_median_multi.py' --data dataset/netcdf --band B02 B03 B04 B08 -- num_workers 16. Attached are the error screenshot about array errors. How much time would it take to precompute the value for scenario 3 typically? i have access to a 72core vCPU.
![image (1)](https://user-images.githubusercontent.com/63696611/213493513-88c42b37-983a-4287-a043-e805e44db92f.png)
![image (2)](https://user-images.githubusercontent.com/63696611/213493522-3dc84059-2641-49ee-94ab-391a3803110e.png)

![image](https://user-images.githubusercontent.com/63696611/213493489-a5742625-d2b7-4e0c-8036-10ac289f7f07.png)

2. Thank you for the information. I am using 8GPU , 64vCPU and 488GB memory with 2TB SSD. 
3. I am trying to simulate this model for Thailand for rice classification. So my approach is to run is as-is for Scenario 3 for France and then modify the code/dataset for Thailand using Sentinel data.

Appreciate your support,

**Comment by paren8esis** [comment]
Thank you for the information.

Please replace [line 43](https://github.com/Orion-AI-Lab/S4A-Models/blob/ae5a3761395cd259724516fa52a89879850558ab/export_medians_multi.py#L43) in `export_medians_multi.py` with the following:

```
medians = sliding_window_view(medians, [num_bins, num_bands, output_size[0], output_size[1]], [1, 1, output_size[0], output_size[1]])[0, 0, :, :, : :, :, :]
```
and see if it works. If it does, then I will update the code.

Regarding your last question, the code should work for other regions too.

**Comment by Krish-newbie** [comment]
Thank you. I will try this and let you know. 
Are there a set of pre-computed medians available for the given 3 scenarios, that can be used directly?

**Comment by Krish-newbie** [comment]
Hi, now i get a different error at line 68. Screenshot attached.

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

![Screenshot 2023-01-20 at 2 59 21 AM](https://user-images.githubusercontent.com/63696611/213535816-279a0e1f-18c7-4282-ac06-e26fea6e5723.png)

**Comment by paren8esis** [comment]
Try to erase line 59:
```
labels = labels.squeeze()
```

**Comment by Krish-newbie** [comment]
Hi, thank you and appreciate your amazing support. I think i am getting there. Facing some error like this OSError: [Errno -101] NetCDF: HDF error: b'dataset/netcdf/2019_31TDK_patch_20_20.nc'. Attached screenshot also.
<img width="1039" alt="Screenshot 2023-01-20 at 12 36 01 PM" src="https://user-images.githubusercontent.com/63696611/213618198-46016b43-a564-4ed3-8b52-34fa55e3af42.png">

**Comment by paren8esis** [comment]
It seems that there is some error with the netcdf file. Please try redownloading it.

**Comment by Krish-newbie** [comment]
Successfully run the medians and saved. Can i ask your help on the command for pad_experiments and visualise_predictions. I want to do it for experiment 3.

**Comment by paren8esis** [comment]
Glad to hear that it runs ok now. I updated the code with the fixes and I am closing this issue.

> Can i ask your help on the command for pad_experiments and visualise_predictions. I want to do it for experiment 3.

There is a detailed description of the commands in the [README](https://github.com/Orion-AI-Lab/S4A-Models#using-the-repo). Please refer to this and if you still have any questions feel free to open a new issue and mark it with the `question` label. I am not able to give you the exact command you should run since it depends on your hardware, paths, etc.
